// groovylint-disable CompileStatic
pipeline {
    agent any 
    stages {
        stage('Clone Repo')
        {
            steps {
                echo 'Cloning the repository'
                sh 'ls -R'
            }
        }
        stage('Build')
        agent {
            docker {
                image 'maven:3.6.3-jdk-8-alpine'
            }
        }
        steps {
            echo 'Building the application'
            dir('multi-app-pipeline/java') {
                sh 'mvn clean package'
            }
        }
    }
        stage('Test java app') {
            agent {
                docker {
                    image 'maven:3.6.3-jdk-8-alpine'
                }
            }
            steps {
                echo 'Running tests for the Java application'
                dir('multi-app-pipeline/java') {
                    sh 'mvn test'
                }
            }
        }

        stage ('Build NODE APP') {
            agent {
                docker {
                    image 'node:14-alpine'
                }
            }
            steps {
                echo 'Building the Node.js application'
                dir('multi-app-pipeline/node') {
                    sh 'npm install'
                    sh 'node app.js'
                }
            }
        }
}
