pipeline {
    agent {
        docker {
            image 'maven:3.6.3-jdk-8-alpine'
        }
    }
    stages {
       stage('Checkout') {
            steps {
                sh 'git clone'
                sh 'git clone https://github.com/royrishwanth/Jenkins-cicd.git' 
            }
        }
        stage('Build') {
            steps {
                sh 'cd java && mvn clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
    }

    agent {
        docker {
            image 'node:16-alpine'
        }
    }
    stages {
        stage('checkout') {
            steps {
                sh 'git clone https://github.com/royrishwanth/Jenkins-cicd.git'
            }
        }
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
}